# 应用名称
spring:
  application:
   name: subjectInfo
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competion_information?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
# 应用服务 WEB 访问端口
server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true